<?php

//use Drupal\Core\Datetime\DrupalDateTime;
//use Drupal\Core\Cache\Cache;
use Symfony\Component\HttpFoundation\RedirectResponse;



function form_example_cancelar () {

  drupal_set_message('Acción Cancelada!!!','error');

  global $base_url;

  //dpm($base_url);

  $response = new RedirectResponse($base_url.'/form_example');
  $response->send();
  return;

}
function form_example_theme($existing, $type, $theme, $path) {
  return [
    'form_example_template' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}

?>
