<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Cache\Cache;


  function alterar_formulario_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    //-----temas de fechas ----------//

    //dia último del mes
    $fecha = new DateTime();
    $fecha->modify('last day of this month');
    $dia=$fecha->format('d');
    $mes=$fecha->format('m');
    $annio=$fecha->format('Y');

    //buscar en la base de base de datos
    //$node = \Drupal::entityManager()->getStorage('node')->load($nid);
    // add libraries


// code to get nid

    if ($form_id=='node_bz_usuarios_form'){
      dpm( $form_id);
      //kint( $form_id);
      ksm($form);
      drupal_set_message('====> nid: '.$node);
      drupal_set_message('DÍA ÚLTIMO DEL MES ====>'.$dia);
      $form['body']['widget']['0']['#placeholder']='Aquí podemos rellenar las incidencias';
      //$form['title']['widget']['0']['value']['#placeholder']="NOMBRE APELLIDO 1 APELLIDO2";
      $form['title']['widget']['0']['#required']=FALSE;
      $form['title']['widget']['0']['value']['#default_value']=t('DAVID ROBLEDO MORANTE');
      //$form['field_fcalta']['widget']['0']['value']['#description']='descripción de la fecha';
      //$form['field_fcalta']['widget']['0']['value']['#default_value']=Drupal\Core\Datetime\DrupalDateTime::createFromTimestamp(time());
      $form['field_fcalta']['widget']['0']['value']['#default_value']=Drupal\Core\Datetime\DrupalDateTime::createFromArray(array('year' => $annio, 'month' => $mes, 'day' => 01) );

    }
    if ($form_id=='node_bz_presencia_form'){
      drupal_set_message('vamos para allá');



    }






  }

  function alterar_formulario_theme($existing, $type, $theme, $path) {

      return array(
          'busqueda' => array(
                                  'variables' => array(
                                      'titulo' => 'Título por defecto',
                                      'descripcion' => 'descripción por defecto',
                                      'formulario'   => NULL
                                      ),
                                  'template' => 'busqueda'
                              )
      );
  }


?>
